CREATE TABLE T_P25R_CUSTOMER(
CUSTOMER_ID NUMBER(8), 
FIRST_NAME VARCHAR2(40), 
LAST_NAME VARCHAR2(40), 
CALLE_DESC VARCHAR2(60), 
CASA_DESC VARCHAR2(4) , 
CONTAC_DESC VARCHAR2(9), 
FEC_REGI DATE
);

ALTER TABLE T_P25R_CUSTOMER
  ADD (
    CONSTRAINT cid_pk PRIMARY KEY (CUSTOMER_ID)
  );
  
CREATE SEQUENCE cid_pk_sequence;

CREATE OR REPLACE TRIGGER customers_on_insert
  BEFORE INSERT ON T_P25R_CUSTOMER
  FOR EACH ROW
BEGIN
  SELECT cid_pk_sequence.nextval
  INTO :new.CUSTOMER_ID
  FROM dual;
END;

--------

--DROP TABLE T_P25R_CUSTOMER CASCADE CONSTRAINTS;

--DELETE FROM T_P25R_CUSTOMER;

select * from T_P25R_CUSTOMER;

